make the congratulation page with confetti in js and correct the road
WildCodeSchool/2023-09-PHP-P2-trilinga pull request #11
Opened 2023-11-11 10:32 UTC by Aude711

2023-11-11 14:56 UTC, Altyrion69 approved these changes

2023-11-12 07:05 UTC, StoicFrenchDev requested changes

2023-11-12 07:05 UTC, StoicFrenchDev commented on src/Controller/QuizController.php
> +    public function indexCongrat(): string
showCongrat() or displayCongrat() would be better function names

2023-11-12 08:19 UTC, StoicFrenchDev approved these changes

2023-11-12 08:19 UTC, merged